name: 'Build and push libre-tools image'
on:
  push:

env:
  DOCKER_HUB_USER: 'blld3eeisj5r'

jobs:
  build-push-image:
    runs-on: 'ubuntu-latest'

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: 'Checkout from github'
        uses: 'actions/checkout@v4'

      -
        name: 'Login to docker hub'
        uses: 'docker/login-action@v3'
        with:
          username: '${{ env.DOCKER_HUB_USER }}'
          password: '${{ secrets.DOCKER_HUB_PAT  }}'

      -
        name: 'Build image'
        uses: 'docker/build-push-action@v5'
        id: 'build'
        with:
          file: 'src/Dockerfile'
          push: true
          tags: '${{ env.DOCKER_HUB_USER}}/libre-tools'
